backend:
    name: git-gateway
    branch: main
media_folder: "/src/img/uploads"
public_folder: "/public/img/uploads"
collections:
    - name: "resources"
      label: "Resources"
      folder: "/resources"
      slug: "{{slug}}"
      create: true
      fields:
          - {
                label: "Layout",
                name: "layout",
                widget: "hidden",
                default: "resource.njk"
            }
          - {
                label: "CSS",
                name: "css",
                widget: "hidden",
                default: "resource.css"
            }
          - {
                label: "Title",
                name: "title",
                widget: "string",
                required: true,
                defualt: "New Post"
            }
          - {
                label: "Description",
                name: "description",
                widget: "string",
                default: "Lorem ipsum dolor sit amet"
            }
          - {
                label: "Tags",
                name: "tags",
                widget: "select",
                multiple: true,
                options: ["course", "ytchannel", "blog"],
                default: "course"
            }
site_url: https://w3Resources.ga
display_url: https://w3Resources.ga
logo_url: https://i.imgur.com/qPntHM6.png

local_backend: false
